config/routes.rb
Rails.application.routes.draw do
  root "pages#rootpage"


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations'
  }


  resources :topics, only: [:index, :show], param: :slug

  #common routes
  get 'home', to: 'courses#index'
  get 'archived-courses', to: 'customers_courses#archived_courses'
  get 'search', to: 'courses#search'
  get 'profile', to: 'customers#show'
  get 'user-home', to: 'customers_courses#customer_home', :as => :user_home
  get 'search', to: 'courses#search', :as => :search_courses
  put 'comment', to: 'comments#create', :as => :create_comment
  post 'add_customer_path' , to: 'customers_courses#insert_careerpath', :as => :add_customer_path
  get 'get_customer_path' , to: 'customers_courses#insert_careerpath', :as => :get_customer_path

  post 'enroll_courses/:slug', to: 'customers_courses#enroll_courses', :as => :enroll_to_course
  post 'courses/:id', to: 'customers_courses#update', :as => :update_archived
  post 'articles/:id', to: 'customers_articles#update', :as => :update_favor
  post 'comments/:id', to: 'comments#update', :as => :update_comment_pin

  post 'archive_courses/:slug', to: 'customers_courses#add_course_to_archived', :as => :add_to_archived
  post 'favor_articles/:id', to: 'customers_articles#add_to_favor', :as => :add_to_favor
  post 'courses/:slug/articles/:id', to: 'customers_courses#click_on_article', :as => :click_on_article
  post 'time', to: 'customers_articles#time', :as => :update_time
  post "/deactivate", to: "admin/customers#deactivate"
  post "/deactivate_course", to: "admin/courses#deactivate_course"
  post "/deactivate_article", to: "admin/articles#deactivate_article"
  post 'update_customer', to: 'customers#update', :as => :update_customer
  post 'update_img', to: 'customers#update_img', :as => :update_img
  get 'update_path', to: 'customers_courses#update_path', :as => :get_update_path
  post 'insert_customer_lo', to: 'paths#insert_customer_lo', :as => :insert_customer_los



  resources :customers do
  end

  resources :customers_courses do
  end

  resources :customers_articles do
  end

  resources :paths do
  end

  resources :courses, only: [:index, :show, :update], param: :slug do
    resources :articles, only: [:index, :show]
  end


  #mentor routes
  namespace :mentor do
    resources :courses
    resources :articles
  end


  #admin routes
  namespace :admin do
    resources :customers, except: :destroy
    resources :users
    resources :courses
    resources :articles, except: [:create, :destroy]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include PgSearch::Model
  #course_article through: course_article
  has_many :course_articles
  has_many :courses, through: :course_articles

  #customer_article through: article_progression
  has_many :customer_articles
  has_many :customers, through: :customer_articles

  has_many :article_skills
  has_many :skills, through: :article_skills

  has_many :article_los
  has_many :los, through: :article_los

  # has_one_attached :image
  pg_search_scope :search_list, against:[
    [:title, 'A']
  ], using: {
    tsearch: {
          prefix: true,
          dictionary: 'english',
          any_word: true,
      },
  }

  scope :by_id, -> (id) { where("id= ?", id)}

  mount_uploader :video, VideoUploader
  accepts_nested_attributes_for :article_los, allow_destroy: true
  accepts_nested_attributes_for :article_skills, allow_destroy: true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController

  def index
    if current_user.customer.role_id != 1
      redirect_to home_path
    end
    @article = if params[:q].present?
                  params[:q].to_i != 0 ? Article.by_id(params[:q]) : Article.search_list(params[:q])
              else
                Article.all.order(created_at: :desc)
              end
    @pagy, @article_paging = pagy(@article, items: 5)
  end

  def deactivate_article
    @article_disable = Article.find(params[:id])
    @article_disable.update(is_active: !@article_disable.is_active)
    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  skip_before_action :verify_authenticity_token
  def index
  end

  def show
    @article_detail = Article.where(id: params[:id])
    @course = Course.friendly.find(params[:course_slug])
    @author = Customer.joins(:customer_courses).where("is_owner = true AND course_id = ? ", @course.id).first
    @is_author = @author.id == current_user.id
    #right side - List article in course
    @list_article_right = Article.joins(:courses).where('courses.id = ?', @course.id).where.not('articles.video.url' => nil).order(id: :asc)
    @list_article_viewed= CustomerArticle.joins(:article).where("is_viewed = true AND customer_id = ? AND article_id IN (?) ",current_user.id, @list_article_right.ids)
    @index_list_article = @list_article_right.pluck(:id).index(@article_detail.ids.first)

    @comment = Comment.new
    @comments = Comment.where(:article_id => @article.id).custom_display  
    @comment_pin = @comments.where("is_pin = true").custom_display.order(updated_at: :desc).limit(1)
    @comment_user = @comments.where("is_pin != true")
    cus_article = CustomerArticle.where("customer_id = ? AND article_id = ?", current_user.id, @article.id)

    if !cus_article.exists?
      CustomerArticle.create(customer_id: current_user.id, article_id: @article.id, time_point: 0.0)
    else
    end
    @cus_article = CustomerArticle.where("customer_id = ? AND article_id = ?", current_user.id, @article.id)
  end

  def get_link_article
    @course_article = Course.joins(:course_articles).where("article_id IN (?) " , @top_view_article.id)
    redirect_to course_path(@course_article)
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :description, :link_article, :tag, :duration, :number_complete, :view_number, :is_free, :link_file_attach)
  end
end

app/controllers/mentor/articles_controller.rb
class Mentor::ArticlesController < Mentor::MentorController
  def new

  end
  def destroy
    @article = Article.find_by(id: params[:id])
    @article.try :destroy
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/favor_articles.html.erb
<%= content_for :page_title, 'Favor article' %>
<body>
<div class="right">
  <h1>
    My course
  </h1>
  <div class="menu-course">
    <ul>
      <li>
        <%= link_to "My courses", "/mycourses" %>
      </li>
      <li>
        <%= link_to "Archive course", "/archived-courses" %>
      </li>
      <li>
        <%= link_to "Favor article", "/favor-articles", style: "color: #F69B58" %>
      </li>
    </ul>
  </div>
  <div class="list-course">
    <% @favor_article.each do |favor_article| %>
      <div class="per-course">
        <div class="c-left">
          <%= image_tag('course_3.jpg') %>
        </div>
        <div class="c-right">
          <h2><%= link_to favor_article.title, course_article_path(favor_article, favor_article.id) %></h2>
          <%= button_to "remove favor", update_favor_path(favor_article.id), method: :put, remote: true %>
          <p><%= favor_article.description %></p>
          <p class="name">Author: <%= favor_article.author %></p>


        </div>
      </div>
    <% end %>
  </div>
  <div class="paging">
    <a href="#">1</a>
    <a href="#">2</a>
    <a href="#">3</a>
    <a href="#">4</a>
    <a href="#">5</a>
  </div>

  <div class="end">
  </div>
</div>

</body>

app/views/articles/show.html.erb
<head>
  <%= content_for :page_title, 'Play article' %>
  <%= stylesheet_link_tag 'watch', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="main-watch">
  <div class="watch">
    <% @article_detail.each do |article| %>
      <% if !article.video.url.nil? %>
        <%= cl_video_tag(article.video.instance_variable_get(:@public_id), :controls => true) %>
      <% end %>
      <div class="w-title">
        <span class="article_title">
          <%= article.title %>
        </span>
        <p>
          <%= article.view_number.to_int.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %> views
          <i class="fa fa-circle"></i>
          Created at:  <%= article.date_created.to_date.strftime("%d/%m/%Y") %>
        </p>

      </div>

      <div class="w-description">
        <div class="w-icon">
          <% if !@author.avatar.nil? %>
            <%= cl_image_tag(@author.avatar) %>
          <% else %>
            <%= image_tag('profile.png') %>
          <% end %>
        </div>
        <div class="w-author">
          <% if !@author.blank? %>
            <p style="font-size: 16px; font-weight: bold"><%= @author.name %></p>
          <% else %>
          <% end %>
        </div>
      </div>
      <% if article.link_file_attach.eql?("N/A") || article.link_file_attach.nil? %>
        Link attach: <%= article.link_file_attach %>

      <% else %>
        Link attach: <a target="_blank" href="<%= article.link_file_attach %>"><%= article.link_file_attach %></a>

      <% end %>
      <p>Description: <%= article.description %></p>
      <div class="w-information">
      </div>
      <div class="comment">
        <div class="account-input">
          <div class="user-icon">
            <% customer = current_user.customer %>
            <div class="avatar">
              <% if !customer.avatar.nil? %>
                <%= cl_image_tag(customer.avatar) %>
              <% else %>
                <%= image_tag('profile.png') %>
              <% end %>
            </div>
          </div>
          <div class="user-input">
            <%= form_for(@comment, html: {class: "input_comment", role: "form", :id => "form_comment", :onsubmit => "checkInput()"}, url: create_comment_path, method: :put, remote: true, require: true) do |f| %>
              <div class="input_comment">
                <%= f.hidden_field :customer_id, value: current_user.id %>
                <%= f.hidden_field :article_id, value: params[:id] %>
                <%= f.text_field :content, id: 'input_cmt', required: true %>
                <%= f.submit onclick: "removeSpace()" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="article_comments">
          <% @comment_pin.each do |pin| %>
            <div class="user-comment">
              <div class="user-icon">
                <% if !pin.customer.avatar.nil? %>
                  <%= cl_image_tag(pin.customer.avatar) %>
                <% else %>
                  <%= image_tag('profile.png') %>
                <% end %>
              </div>
              <div class="user-right">
                <div class="user-name" style="font-weight: bold">
                  <%= pin.customer.name %>
                </div>
                <div class="u-comment pin">
                  <%= pin.content %>
                </div>
              </div>

              <div class="comment_pin">
                <% current_role = Customer.where("user_id = ? AND role_id = 2", current_user.id) %>
                <% if !current_role.blank? %>
                  <%= link_to update_comment_pin_path(pin.id), method: :post, remote: true do %>
                    <i class="fa fa-times" onclick="check(this)" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
          <% @comment_user.each do |comment| %>
            <%= render "comments/comment", comment: comment %>
          <% end %>
          <div class="user-comments">
            <% @comment_user.each do |comment| %>
              <%= render partial: "comments/comment", locals: {comment: comment, is_author: @is_author} %>
            <% end %>
          </div>
        </div>
        <div style="height: 300px" class="end">
        </div>
    <% end %>
    </div>
  </div>
  <div class="list">
    <p style="font-size: 20px; font-weight: bold; margin-top: 0">List article in course</p>
    <div class="list-video">
      <ul>
        <% @list_article_right.each do |a| %>
          <li>
            <div class="l-left">
            <% if !a.video.url.nil? %>
              <%= cl_video_tag(a.video.instance_variable_get(:@public_id), :effect => "preview", :resource_type => "video") %>
            <% end %>
              <i class="fa fa-check-circle" aria-hidden="true"></i>
            </div>
            <div class="l-right">
              <% article = CustomerArticle.where("customer_id = ? AND article_id = ?", current_user.id, a.id) %>
              <% if article.exists? %>
                <% if article.first.is_favor == true %>
                  <%= link_to update_favor_path(a.id), method: :post, remote: true do %>
                    <i style="" onclick="bookmark(this,123)" class="fa fa-heart" id="article_id<%= a.id %>" aria-hidden="true"></i>
                  <% end %>
                <% else %>
                  <%= link_to update_favor_path(a.id), method: :post, remote: true do %>
                    <i style="" onclick="bookmark(this,123)" class="fa fa-heart-o" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              <% else %>
                <%= link_to add_to_favor_path(a.id), method: :post do %>
                  <i style="" onclick="bookmark(this,123)" class="fa fa-heart-o" aria-hidden="true"></i>
                <% end %>
              <% end %>
              <div class="l-title">
                <%= link_to a.title, course_article_path(params[:course_slug], a.id) %>
              </div>
              <div class="l-author">
                <% if !@author.blank? %>
                  <%= @author.name %><br>
                <% else %>
                <% end %>
              </div>
              <div class="l-view">
                 <%= a.view_number.to_int.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %> views
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<script>
    $(document).ready(() => {

        $('video').attr('controlsList', 'nodownload');

    });
</script>


<script>
    var arr = document.getElementsByTagName('li');
    var index = <%= @index_list_article.to_int %>; //8 is index of video in list
    var size = <%=  @list_article_right.count.to_int %>;
    arr[index].style.border = "1px solid #14bdee";
    arr[index].style.borderRadius = "5px";
    arr[index].style.backgroundColor = "#f2f2f0";
    document.getElementsByClassName('list-video')[0].scrollTop = index * 85;
</script>
<!--begin of get currentTime and total duration-->
<script>
    var index = <%= @index_list_article.to_int %>;
    document.getElementsByTagName('video')[0].currentTime = <%= @cus_article.first.time_point %>;
    var count = -1;
    <% @list_article_right.each do | full | %>
    count++;
    <% @list_article_viewed.each do |view| %>
    <% if view.article_id == full.id %>
    document.querySelectorAll('.fa-check-circle')[count].style.display = 'inline-block';
    <% end %>
    <% end %>
    <% end %>
    setInterval(function () {
        var currentTime = document.getElementsByTagName('video')[0].currentTime;
        var total = document.getElementsByTagName('video')[0].duration;
        var calculate = (currentTime / total) * 100;
        var isViewed = false;
        if (calculate >= 90) {
            document.querySelectorAll('.fa-check-circle')[index].style.display = 'inline-block';
            isViewed = true;
            $.ajax({
                url: "/time",
                data: {"currentTime": currentTime, "isViewed": isViewed, "id": <%= params[:id] %>},
                type: "POST",
                success: function (data) {
                    console.log(data);
                }
            });
        }
    }, 1000);
    document.getElementsByTagName('video')[0].onpause = function () {
        var currentTime = this.currentTime;
        var total = this.duration;
        var calculate = (currentTime / total) * 100;
        var isViewed = false;
        if (calculate >= 90) {
            isViewed = true;
        } else
            isViewed = false
        $.ajax({
            url: "/time",
            data: {"currentTime": currentTime, "isViewed": isViewed, "id": <%= params[:id] %>},
            type: "POST",
            success: function (data) {
                console.log(data);
            }
        });
    };
</script>
<!--end of get currentTime and total duration-->
<script>
    function bookmark(heart, courseID) {
        var x = heart;
        if (x.className === "fa fa-heart") {
            x.className = "fa fa-heart-o";
        } else {
            x.className = "fa fa-heart";
        }
        var app1 = new Vue({
            el: '#app1',
            mounted: function () {
                axios.get('/archive_courses/', {
                    params: {
                        num: courseID
                    }
                }).catch(error => {
                    console.log(error);
                });
            }
        });
    }
</script>

<script>
    function check(heart, courseID) {
        var x = heart;
        if (x.className === "fa fa-check") {
            x.className = "fa fa-times";
        } else {
            x.className = "fa fa-check";
        }
        var app1 = new Vue({
            el: '#app1',
            mounted: function () {
                axios.get('//', {
                    params: {
                        num: courseID
                    }
                }).catch(error => {
                    console.log(error);
                });
            }
        });
    }
</script>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        $('#videoElementID').bind('contextmenu', function () {
            return false;
        });
    });
</script>

<script>
    function removeSpace() {
        document.getElementById('input_cmt').value =
            document.getElementById('input_cmt').value.trim();

    }

    function checkInput() {
        if (document.getElementById('input_cmt').value.trim() == "") {
            return false;
        }
        return true;
    }
</script>

</body>

app/views/articles/update.js.erb
var $is_pinId = $('#is_pin<%= @update_comment.id %>')
<%# binding.pry %>

<% if params[:pin_cmt] %>
$is_pinId.addClass("user-comment")
<% else %>

<% end %>