config/routes.rb
Rails.application.routes.draw do
  root "pages#rootpage"


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations'
  }


  resources :topics, only: [:index, :show], param: :slug

  #common routes
  get 'home', to: 'courses#index'
  get 'archived-courses', to: 'customers_courses#archived_courses'
  get 'search', to: 'courses#search'
  get 'profile', to: 'customers#show'
  get 'user-home', to: 'customers_courses#customer_home', :as => :user_home
  get 'search', to: 'courses#search', :as => :search_courses
  put 'comment', to: 'comments#create', :as => :create_comment
  post 'add_customer_path' , to: 'customers_courses#insert_careerpath', :as => :add_customer_path
  get 'get_customer_path' , to: 'customers_courses#insert_careerpath', :as => :get_customer_path

  post 'enroll_courses/:slug', to: 'customers_courses#enroll_courses', :as => :enroll_to_course
  post 'courses/:id', to: 'customers_courses#update', :as => :update_archived
  post 'articles/:id', to: 'customers_articles#update', :as => :update_favor
  post 'comments/:id', to: 'comments#update', :as => :update_comment_pin

  post 'archive_courses/:slug', to: 'customers_courses#add_course_to_archived', :as => :add_to_archived
  post 'favor_articles/:id', to: 'customers_articles#add_to_favor', :as => :add_to_favor
  post 'courses/:slug/articles/:id', to: 'customers_courses#click_on_article', :as => :click_on_article
  post 'time', to: 'customers_articles#time', :as => :update_time
  post "/deactivate", to: "admin/customers#deactivate"
  post "/deactivate_course", to: "admin/courses#deactivate_course"
  post "/deactivate_article", to: "admin/articles#deactivate_article"
  post 'update_customer', to: 'customers#update', :as => :update_customer
  post 'update_img', to: 'customers#update_img', :as => :update_img
  get 'update_path', to: 'customers_courses#update_path', :as => :get_update_path
  post 'insert_customer_lo', to: 'paths#insert_customer_lo', :as => :insert_customer_los



  resources :customers do
  end

  resources :customers_courses do
  end

  resources :customers_articles do
  end

  resources :paths do
  end

  resources :courses, only: [:index, :show, :update], param: :slug do
    resources :articles, only: [:index, :show]
  end


  #mentor routes
  namespace :mentor do
    resources :courses
    resources :articles
  end


  #admin routes
  namespace :admin do
    resources :customers, except: :destroy
    resources :users
    resources :courses
    resources :articles, except: [:create, :destroy]
  end
end

app/views/shared/ _pagination.html.erb
<% link = pagy_link_proc(pagy) %>
<nav aria-label="pager" class="table-pagination" role="navigation">
  <ul class="pagination">
    <% if pagy.prev %>
      <li class="page-item">
        <%== link.call(pagy.prev, '<span class="icon-ic-arrow-left page-link__previous" aria-hidden="true"></span>', 'aria-label="previous" class="page-link"') %>
      </li>
    <% else %>
      <li class="page-item disabled">
        <%==link.call(1, '<span class="icon-ic-arrow-left page-link__previous" aria-hidden="true"></span>', 'class="page-link"') %>
      </li>
    <% end %>
    <% pagy.series.each do |item| %>
      <% if item.is_a?(Integer) %>
        <li class="page-item">
          <%== link.call(item, item, 'class=page-link') %>
        </li>
      <% elsif item.is_a?(String) %>
        <li class="page-item active">
          <%= link_to(item, "javascript:void(0)", class: "page-link") %>
        </li>
      <% elsif item == :gap %>
        <li class="page-item disabled">
          <%== link_to("...", "javascript:void(0)", class: "page-link") %>
        </li>
      <% end %>
    <% end %>
    <% if pagy.next %>
      <li class="page-item">
        <%== link.call(pagy.next, '<span class="icon-ic-arrow-right page-link__next" aria-hidden="true"></span>', 'aria-label="next" class="page-link"') %>
      </li>
    <% else %>
      <li class="page-item disabled">
        <%== link.call(pagy.last, '<span class="icon-ic-arrow-right page-link__next" aria-hidden="true"></span>', 'class="page-link"') %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_admin_left_side.html.erb
<div class="left">
  <h2>Menu</h2>
  <ul class="top">
    <li>
      <a href="#">
        <i style="color: #2bc3cc;" class="fa fa-home"></i> Home
      </a>
    </li>
    <li>
      <%= link_to wizard_path(:over_view) do %>
        <i style="color: #2bc3cc;" class="fa fa-plus-circle"></i> New Course
      <% end %>
    </li>
  </ul>
  <h2>Topic</h2>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="per_col">
    <div class="footer_logo_container">
      <a href="#">
        <div class="footer_logo_text">Edfective<span>ly</span></div>
      </a>
    </div>
    <div class="footer_about_text">
      <p>Best choice, best learning</p>
    </div>
    <div class="footer_social">
      <ul>
        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="per_col">
    <div class="footer_title">Contact Us</div>
    <div class="footer_contact_info">
      <ul>
        <li>Email: edfectively@gmail.com</li>
        <li>Phone: 0345-666-656</li>
        <li>FPT University - Hoa Lac - Thach That - Ha Noi</li>
      </ul>
    </div>
  </div>
  <div class="per_col">
    <div class="footer_title">Contact Us</div>
    <div class="footer_links_container">
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Features</a></li>
        <li><a href="#">Courses</a></li>
        <li><a href="#">Events</a></li>
        <li><a href="#">Gallery</a></li>
        <li><a href="#">FAQs</a></li>
      </ul>
    </div>
  </div>
  <div class="per_col">
    <div class="footer_title">Mobile</div>
    <div class="footer_mobile_content">
      <div class="footer_image">
        <a href="#"><%= image_tag('mobile_1.png') %></a>
      </div>
      <div class="footer_image">
        <a href="#"><%= image_tag('mobile_2.png') %></a>
      </div>
    </div>
  </div>

</div>

app/views/shared/_header.html.erb
<div id="header">
  <div class="menu">
    <div class="logo">
      <% if !current_user.present? %>
        <a onclick="myFunction()" href="/home">
          <%= image_tag("logo_1.PNG") %>
          <span>Edfective</span><span style="color: #14bdee;">ly</span>
        </a>
      <% else %>
        <% if !request.original_fullpath.include? "/mentor" %>
          <a onclick="myFunction()" href="/user-home">
            <%= image_tag("logo_1.PNG") %>
            <span>Edfective</span><span style="color: #14bdee;">ly</span>
          </a>
        <% else %>
          <a onclick="myFunction()" href="/mentor/courses">
            <%= image_tag("logo_1.PNG") %>
            <span>Edfective</span><span style="color: #14bdee;">ly</span>
          </a>
        <% end %>
      <% end %>
    </div>

    <%= form_tag search_courses_path, :html => { :onsubmit => "checkInput()" }, class: "search", method: :get do %>
      <%= text_field_tag 'q', params[:q], placeholder: "Search a Courses...", required: true,:id => 'input', autocomplete: "off" %>
      <button onclick="removeSpace()" type="submit">
        <%= image_tag("search.png") %>
      </button>
    <% end %>
    <% if !current_user.present? %>
      <div class="user">
        <a class="login" href="/users/sign_in">Sign in</a>
        <a class="signup" href="/users/sign_up">Sign up</a>
      </div>
    <% else %>
      <div class="user">
<!--        <a href="#">-->
<!--          <i class="fa fa-bell"></i>-->
<!--        </a>-->
        <%= link_to "#", :onMouseover => "myfunction()", id:"myBtn" do %>
          <% customer = current_user.customer %>
          <% if !customer.avatar.nil? %>
            <%= cl_image_tag(customer.avatar, :height=>100, :width=>50)%>
          <% else %>
            <%= cl_image_tag('img/profile_mvh34m.png', :height=>100, :width=>50)%>
          <% end %>
          <a href="" class="profile"></a>
        <% end %>
        <div id="notifications" style="margin-top: 13px;">
<!--           <h3>Information User</h3>-->
          <div class="show_menu">
            <p>
              <a href="">
                <i class="fa fa-user-circle-o"></i>
                <%= link_to " Profile", profile_path %>
              </a>
            </p>
            <p>
              <a href="">
                <i class="fa fa-star"></i>
                <%= link_to "Career path" , paths_path %>
              </a>
            </p>
            <p>
              <a href="">
                <i class="fa fa-sign-out"></i>
                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
              </a>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>
    window.addEventListener('click', function(e) {
        if (!document.getElementById('myBtn').contains(e.target)) {
            document.getElementById('notifications').style.display = "none"
        }
    });

    function myfunction() {
        if (document.getElementById('notifications').style.display == "none" ||
            document.getElementById('notifications').style.display == '') {
            document.getElementById('notifications').style.display = "block"
        } else {
            document.getElementById('notifications').style.display = "none"
        }
    }
</script>
<script>
    function removeSpace() {
        document.getElementById('input').value =
            document.getElementById('input').value.trim();
    }

    function checkInput() {
        if (document.getElementById('input').value.trim() == "") {
            return false;
        }
        return true;
    }
</script>

app/views/shared/_header_admin.html.erb
<div id="header">
  <div class="menu">
    <div  class="logo">
      <% if !current_user.present? %>
        <a href="/home">
          <%= image_tag("logo_1.PNG") %>
          <span>Edfective</span><span style="color: #14bdee;">ly</span>
        </a>
      <% else %>
        <a href="/user-home">
          <%= image_tag("logo_1.PNG") %>
          <span>Edfective</span><span style="color: #14bdee;">ly</span>
        </a>
      <% end %>
    </div>

    <form>

    </form>

    <% if !current_user.present? %>
      <div class="user">
        <a class="login" href="/users/sign_in">Sign in</a>
        <a class="signup" href="/users/sign_up">Sign up</a>
      </div>
    <% else %>
      <div class="user">
        <%= link_to profile_path, :onMouseover => "myfunction()", id:"myBtn" do %>
            <%#= cl_image_tag('4.png', :height=>100, :width=>50)%>
          <%= image_tag("4.png") %>
        <% end %>
        <%#= link_to "Logout", destroy_user_session_path, method: :delete %>
        <div id="notifications" style="margin-top: 13px;">
          <!-- <h3>Information User</h3> -->
          <div class="show_menu">
            <p>
              <a href="">
                <i class="fa fa-user-circle-o"></i>
                <%= link_to " Profile", profile_path %>
              </a>
            </p>
<!--            <p>-->
<!--              <a href="">-->
<!--                <i class="fa fa-star"></i>-->
                <%#= link_to "Career path" , paths_path %>
<!--              </a>-->
<!--            </p>-->
            <p>
              <a href="">
                <i class="fa fa-sign-out"></i>
                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
              </a>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>
    window.addEventListener('click', function(e) {
        if (!document.getElementById('myBtn').contains(e.target)) {
            document.getElementById('notifications').style.display = "none"
        }
    });

    function myfunction() {
        if (document.getElementById('notifications').style.display == "none" ||
            document.getElementById('notifications').style.display == '') {
            document.getElementById('notifications').style.display = "block"
        } else {
            document.getElementById('notifications').style.display = "none"
        }
    }
</script>
<script>
    function removeSpace() {
        document.getElementById('input').value =
            document.getElementById('input').value.trim();
    }

    function checkInput() {
        if (document.getElementById('input').value.trim() == "") {
            return false;
        }
        return true;
    }
</script>

app/views/shared/_left_side.html.erb
<div class="left">
  <h2>Menu</h2>
  <ul class="top">
    <li>
      <% if !current_user.present? %>
        <a onclick="myFunction()" href="/home">
          <i class="fa fa-home"></i> Home Page
        </a>
      <% else %>
        <a onclick="myFunction()" href="/user-home">
          <i class="fa fa-home"></i> Home Page
        </a>
      <% end %>
    </li>
    <% if !current_user.present? %>
      <li>
        <%= link_to new_user_session_path do %>
          <i class="fa fa-user-circle-o"></i> Sign in
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path do %>
          <i class="fa fa-user-circle-o"></i> Sign up
        <% end %>
      </li>
    <% else %>
      <li>
        <a onclick="myFunction()" href="/customers_courses">
          <i class="fa fa-laptop"></i> My Course
        </a>
      </li>
    <% end %>

    <% if current_user.present? %>
      <% current_role = Customer.where("user_id = ? AND role_id = 2", current_user.id) %>
      <% if !current_role.blank? %>
        <% if !request.original_fullpath.include? "/mentor" %>
          <li>
            <%= link_to mentor_courses_path do %>
              <i class="fa fa-user-circle-o"></i> Working as Mentor
            <% end %>
          </li>
        <% else %>  
          <li>
            <%= link_to '/user-home' do %>
              <i class="fa fa-user-circle-o"></i> Working as Student
            <% end %> 
          </li>
        <% end %>
      <% else %>
      <% end %>
    <% else %>
    <% end %>
  </ul>
  <% if current_user.present? %>
    <h2 id="follow_text">Follow</h2>
    <ul class="top" id="follow">
      <% course.each do |a| %>
        <li>
          <%= link_to course_path(a.slug) do %>
            <i class="fa fa-graduation-cap"></i>
            <%= a.name %>
          <% end %>
        </li>
      <% end %>
      <li class="show" onclick="showMore()">
        <a href="/customers_courses">
          <i class="fa fa-sort-down"></i>Show all
        </a>
      </li>
    </ul>
  <% end %>



  <% if !current_user.present? %>
    <h2>Groups</h2>
    <ul class="top">
      <% data.each do |c| %>
        <li>
          <%= link_to topic_path(c.slug) do %>
            <i class="fa fa-graduation-cap"></i>
            <%= c.name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
  <% end %>
</div>
<script>
    <% if current_user.present? %>
    <%  @number_enroll = CustomerCourse.where('customer_id = ? AND customer_courses.enrollment_date IS NOT null', current_user.id) %>
    var amountLeftSide =  <%=  @number_enroll.count.to_int %>;
    <% else %>
    var amountLeftSide = 6
    <% end %>
    var size = 1;
    if (amountLeftSide <= 5 * size) {
        document.getElementsByClassName('show')[0].style.display = "none";
    }

    function showMore() {
        size++;
    }
</script>

<script>
    <% if current_user.present? %>
    var x11 = <%=course.length %>
    <% else %>
    var x11 = 0
    <% end %>
    if (x11 == 0) {
        document.getElementById('follow').style.borderBottom = "none";
        document.getElementById('follow_text').style.display = "none";
    }
</script>

app/views/shared/_left_side_admin.html.erb
<div class="left">
  <h2>Menu</h2>
  <ul class="top">
    <li>
      <a href="/admin/customers">
        Manager Account
      </a>
    </li>
    <li>
      <a href="/admin/courses">
        Manager Course
      </a>
    </li>
    <li>
      <a href="/admin/articles">
        Manager Article
      </a>
    </li>
    <li>
      <a href="/admin/groups">
        Manager Group
      </a>
    </li>
  </ul>
</div>
<script>
    var url = "<%= url_for(only_path: false) %>";
    var li = document.getElementsByTagName('li');
    if (url.endsWith("customers")) {
        li[0].style.border = "2px solid #14bdee";
    } else if (url.endsWith("courses")) {
        li[1].style.border = "2px solid #14bdee";
    } else if (url.endsWith("articles")) {
        li[2].style.border = "2px solid #14bdee";
    }  else if (url.endsWith("articles")) {
        li[3].style.border = "2px solid #14bdee";
    }
</script>

app/views/shared/_messages.html.erb
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 