config/routes.rb
Rails.application.routes.draw do
  root "pages#rootpage"


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations'
  }


  resources :topics, only: [:index, :show], param: :slug

  #common routes
  get 'home', to: 'courses#index'
  get 'archived-courses', to: 'customers_courses#archived_courses'
  get 'search', to: 'courses#search'
  get 'profile', to: 'customers#show'
  get 'user-home', to: 'customers_courses#customer_home', :as => :user_home
  get 'search', to: 'courses#search', :as => :search_courses
  put 'comment', to: 'comments#create', :as => :create_comment
  post 'add_customer_path' , to: 'customers_courses#insert_careerpath', :as => :add_customer_path
  get 'get_customer_path' , to: 'customers_courses#insert_careerpath', :as => :get_customer_path

  post 'enroll_courses/:slug', to: 'customers_courses#enroll_courses', :as => :enroll_to_course
  post 'courses/:id', to: 'customers_courses#update', :as => :update_archived
  post 'articles/:id', to: 'customers_articles#update', :as => :update_favor
  post 'comments/:id', to: 'comments#update', :as => :update_comment_pin

  post 'archive_courses/:slug', to: 'customers_courses#add_course_to_archived', :as => :add_to_archived
  post 'favor_articles/:id', to: 'customers_articles#add_to_favor', :as => :add_to_favor
  post 'courses/:slug/articles/:id', to: 'customers_courses#click_on_article', :as => :click_on_article
  post 'time', to: 'customers_articles#time', :as => :update_time
  post "/deactivate", to: "admin/customers#deactivate"
  post "/deactivate_course", to: "admin/courses#deactivate_course"
  post "/deactivate_article", to: "admin/articles#deactivate_article"
  post 'update_customer', to: 'customers#update', :as => :update_customer
  post 'update_img', to: 'customers#update_img', :as => :update_img
  get 'update_path', to: 'customers_courses#update_path', :as => :get_update_path
  post 'insert_customer_lo', to: 'paths#insert_customer_lo', :as => :insert_customer_los



  resources :customers do
  end

  resources :customers_courses do
  end

  resources :customers_articles do
  end

  resources :paths do
  end

  resources :courses, only: [:index, :show, :update], param: :slug do
    resources :articles, only: [:index, :show]
  end


  #mentor routes
  namespace :mentor do
    resources :courses
    resources :articles
  end


  #admin routes
  namespace :admin do
    resources :customers, except: :destroy
    resources :users
    resources :courses
    resources :articles, except: [:create, :destroy]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include PgSearch::Model
  #course_article through: course_article
  has_many :course_articles
  has_many :courses, through: :course_articles

  #customer_article through: article_progression
  has_many :customer_articles
  has_many :customers, through: :customer_articles

  has_many :article_skills
  has_many :skills, through: :article_skills

  has_many :article_los
  has_many :los, through: :article_los

  # has_one_attached :image
  pg_search_scope :search_list, against:[
    [:title, 'A']
  ], using: {
    tsearch: {
          prefix: true,
          dictionary: 'english',
          any_word: true,
      },
  }

  scope :by_id, -> (id) { where("id= ?", id)}

  mount_uploader :video, VideoUploader
  accepts_nested_attributes_for :article_los, allow_destroy: true
  accepts_nested_attributes_for :article_skills, allow_destroy: true
end

app/models/course.rb
class Course < ApplicationRecord

  include PgSearch::Model
  before_create :update_slug
  before_create :check_for_duplicates?

  def check_for_duplicates?
    if !Course.find_by(:name => self.name).nil?
      self.slug = (name + 10.times.map{rand(10)}.join).parameterize
    end
  end
  validates :name, uniqueness: true, on: :landing_page

  extend FriendlyId
  friendly_id :name, use: [:slugged]

  pg_search_scope :search, against:[
      [:name, 'A'],
      [:description, 'B']
  ], using: {
      tsearch: {
          prefix: true,
          dictionary: 'english',
          any_word: true,
      },
  }

  pg_search_scope :search_list, against:[
    [:name, 'A']
  ], using: {
    tsearch: {
          prefix: true,
          dictionary: 'english',
          any_word: true,
      },
  }

  scope :by_id, ->(id) { where("id= ?", id)}
  scope :by_rates, ->(rate) { where("rate = ?", rate)}
  scope :by_levels, ->(level) { where("level = ?", level)}
  scope :by_prices, ->(price) { where("price = ?", price)}

  STEPS = %i(landing_page create_content over_view)

  has_many :course_groups
  has_many :groups, through: :course_groups

  has_many :course_articles
  has_many :articles, through: :course_articles

  has_many :customer_courses
  has_many :customers, through: :customer_courses

  accepts_nested_attributes_for :articles
  accepts_nested_attributes_for :course_groups
  accepts_nested_attributes_for :customer_courses

  def update_slug
    self.slug = name.parameterize
  end

  def to_params
    slug
  end

  def should_generate_new_friendly_id?
    name_changed? || super
  end

  mount_uploader :image, ImageUploader

end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::AdminController

  def index
    if current_user.customer.role_id != 1
      redirect_to home_path
    end
    @course = if params[:q].present?
                params[:q].to_i != 0 ? Course.by_id(params[:q]) : Course.search_list(params[:q])
              else
                Course.all
              end
    @pagy, @course_paging = pagy(@course, items: 10)
  end

  def deactivate_course
    @course_disable = Course.friendly.find(params[:slug])
    @course_disable.update(is_active: !@course_disable.is_active)
    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_course, only: [:show]

  def index
    if current_user.present?
      redirect_to user_home_path
    end
    @course = Course.where(:is_active => true).order(number_enrollment: :desc).limit(20)
    @rate_course = Course.where(:is_active => true).order(rate: :desc).limit(20)
    @free_course = Course.where(:is_active => true).where(is_free: true).limit(20)
    @topic = Group.all
    @top_view_article = Article.where(:is_active => true).order(view_number: :desc).limit(20)
  end

  def show
    course_lo_str = Course.where('courses.id = ?', @course.id)
    if course_lo_str.first.lo.present?
      @course_lo_arr = course_lo_str.first.lo.tr('', '').split(';').map(&:to_i)
      @list_lo = Lo.where("id IN (?)", @course_lo_arr).group(:id)
      # @skill = Skill.where("id IN (?)", @list_lo.pluck(:skill_id).uniq)
      lo_req = LoLo.where("lo_id IN (?)", @course_lo_arr)
      req = lo_req.pluck(:lo_req_id).uniq
      @lo_req = Lo.where("id IN (?)", req)
    else
      @lo_req = []
      @list_lo = []
    end

    if current_user.present?
      @check_archived_course = CustomerCourse.where('customer_id = ? AND course_id = ? AND customer_courses.enrollment_date IS null', current_user.id, @course.id)
      if !@check_archived_course.blank?
        @course_detail = Course.select("courses.*, customer_courses.*").joins(:customer_courses).where('customer_id = ? AND course_id = ?', current_user.id, @course.id)
      else
        calculate_progression
      end
    else
      @course_detail = Course.where('course_id = ?', @course.id)
    end
    @list_articles = Article.joins(:courses).where('courses.id = ?', @course.id).where.not('articles.video.url' => nil).order(id: :asc)
    if current_user.present?
      @list_article_viewed = CustomerArticle.joins(:article).where("is_viewed = true AND customer_id = ? AND article_id IN (?) ", current_user.id, @list_articles.ids)
    end
    @pagy, @list_article_paging = pagy(@list_articles, items: 5)
  end

  def calculate_progression
    total_article = Article.joins(:course_articles).where('course_id = ?', @course.id).count
    viewed_article = Article.joins(:course_articles).joins(:customer_articles).where('course_id = ? AND is_viewed = true', @course.id).count
    #fix exception FloatDomainError
    if total_article == 0
      progress = 0
    else
      progress = viewed_article.to_f / total_article.to_f * 100
    end
    @customers_courses_progression = CustomerCourse.where(customer_id: current_user.id, course_id: @course.id)
    @customers_courses_progression.update(progression: progress.round) # => progression
  end

  def search
    if params[:q].present?
      @search_result = Course.search(params[:q])
      @pagy, @search_result_paging = pagy(@search_result, items: 5)
    else
      @search_result = []
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def authenticate_user!
    if user_signed_in?
      # super
    else
      redirect_to user_home_path
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.friendly.find(params[:slug])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:name, :image, :description, :is_free, :is_save, :is_owner, :rate, :number_enrollment, :enrollment_date)
  end

end

app/controllers/mentor/articles_controller.rb
class Mentor::ArticlesController < Mentor::MentorController
  def new

  end
  def destroy
    @article = Article.find_by(id: params[:id])
    @article.try :destroy
  end
end

app/controllers/mentor/courses_controller.rb
class Mentor::CoursesController < Mentor::MentorController
  include Wicked::Wizard
  before_action :load_course, except: :index
  steps :landing_page, :create_content, :over_view

  def index
    if session[:course_id] != nil
      session[:course_id] = nil
    end
    @pagy ,@mentor_course = pagy(Course.joins(:customer_courses).joins(:customers).where('customers.id = ? AND customer_courses.is_owner = true', current_user.id).order(created_at: :desc), items: 5)
    
  end

  def new
  end

  def show
    @step = step
    if session[:course_id] != nil
      @current_course = @course
    end
    render_wizard
  end

  def update 
    @step = step.to_s
    @course.assign_attributes course_params
    unless step.to_sym == :create_content
      @course.id = Course.last.id.next unless @course.id
      @course.author = current_user.id
      session[:course_id] = @course.id
      begin
        render_wizard @course
      rescue
        flash[:error] = @course.errors.full_messages
      end
    else
      los = []
      @course.articles.each do |article| 
        article.los.each do |lo|
          los << lo.id
        end
      end
      @course.duration += ('%.2f' % (params[:article_duration].to_f / 360 )).to_f
      los = los.uniq
      @course.lo = los.join(";")   
      if step.to_sym == :create_content
        if @course.save
          redirect_to wizard_path(:create_content)
        else
          flash[:error] = @course.errors.full_messages
        end
      end
    end
  end

  private
  def course_params
    params.require(:course).permit!
  end

  def load_course
    if session[:course_id].nil? && step.to_sym != :landing_page
      redirect_to wizard_path(:landing_page)
    elsif step.to_sym == :landing_page && session[:course_id].nil?
        @course = Course.new
    elsif !session[:course_id].nil?
      @course = Course.find_by id: session[:course_id]
      if @course.nil?
        redirect_to mentor_courses_path
      end
    else
      @course = Course.find_by slug: params[:id]
    end
  end
end

app/controllers/mentor/mentor_controller.rb
class Mentor::MentorController < ApplicationController
  before_action :authenticate_user!
  before_action :check_metor_account

  private
  def check_metor_account
    if current_user.customer.role_id != 2
      redirect_to home_path
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/mentor/courses/_course.html.erb
<% articles.each do |article| %>
  <% if article.title != nil %>
    <div id='container_show' class='<%="article-#{article.id}"%> per-course'>
      <div class="c-left create_content-left">
        <% if !article.video.url.nil? %>
          <%= video_tag article.video.url, 
            :size => "320x240", :controls => true %>
        <% else %>
          <%= image_tag("course_8.jpg") %>
          <%#= cl_video_tag('video/Introduction_to_the_Course_-_Introduction_to_the_Course_-_Coursera_jqhxzg', :effect => "preview", :resource_type => "video") %>
        <% end %>
      </div>
      <div class="c-right create_content">
        <%= link_to mentor_article_path(article), method: :delete, confirm: "Are you sure?", remote: true  do %>
          <i class="fa fa-trash" aria-hidden="true"></i>
        <% end %>
        <a href="#">
          <%= article.title %>
        </a>
        <span>
          <%= article.description %>
        </span>
        <div class="more-infor">
            <% article.los.each do |lo| %>
              <span> <%= lo.name %> </span>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/mentor/courses/_process.html.erb
<head>
  <%= stylesheet_link_tag 'upload', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<div class="process">
  <div class="process">
    <%= link_to previous_wizard_path, class: "previous" do %>
      <i class="fa fa-step-backward" aria-hidden="true"></i>
    <% end %>
    <% disable = session[:course_id].nil? ? "disable-click" : "" %>
    <%= link_to wizard_path(:landing_page), class: "landing_page" do %>
      <i class="fa fa-check-circle <%= 'active' if step.to_s == 'landing_page' %>"></i>
    <% end %>
    <%= link_to wizard_path(:create_content), class: "create_content #{disable}" do %>
      <i class="fa fa-check-circle <%= 'active' if step.to_s == 'create_content' %>" aria-hidden="true"></i>
    <% end %>
    <%= link_to wizard_path(:over_view), class: "over_view #{disable}" do %>
      <i class="fa fa-check-circle <%= 'active' if step.to_s == 'over_view' %>" aria-hidden="true"></i>
    <% end %>
    <%= link_to next_wizard_path, class: "next" do %>
      <i class="fa fa-step-forward" aria-hidden="true"></i>
    <% end %>
  </div>
</div>

app/views/mentor/courses/create_content.html.erb
<head>
  <%= stylesheet_link_tag 'upload', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
</head>
<div id="right" class="right">
<%= render "process", step: @step  %>
<h1>Step 2: Create Articles in "<%= @course.name %>"</h1>
  <div id="form_upload" class="form-upload">
    <%= form_with model: @course, html: {:onsubmit =>"myFunction()"}, url: wizard_path, method: :put, class: "form_upload" do |f| %>
      <%= f.fields_for :articles, f.object.articles.build do |ff| %>
          <div class="information-video">
            <div class="per_row_article">
              <div class="row-left">
                <h2>Video</h2>
              </div>
              <div class="row-right">
                <video style="display: none" id="video_upload" width="320" height="240" controls>
                </video>
                <div class="thum">
                  <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                  <p>Upload video</p>
                  <%= ff.file_field :video, :required => true %>
                </div>
              </div>
            </div>
            <div class="per_row_article">
              <div class="row-left">
                <h2>Title</h2>
              </div>
              <div class="row-right">
                <%= ff.text_field :title, class: "title_article", placeholder: "Title",:required => true %>
              </div>
            </div>
            <div class="per_row_article">
              <div class="row-left">
                <h2>Description</h2>
              </div>
              <div class="row-right">
                <%= ff.text_area :description, class: "desc_course", placeholder: "Description", :required => true %>
              </div>
            </div>
            <div class="per_row_article">
              <div class="row-left">
                <h2>Learning Outcomes</h2>
              </div>
              <div class="row-right">
              <%= ff.select :lo_ids, (Lo.by_skill_ids(Skill.by_group_ids(@course.groups.ids))).name_and_id, {}, {:class => "js-example-basic-multiple", :multiple => "multiple"} %>
              </div>
            </div>
            <div class="per_row_article">
              <div class="row-left">
                <h2>Attached file</h2>
              </div>
              <div class="row-right">      
                <%= ff.text_field :link_file_attach, class: "title_article", placeholder: "Link attached file" %>       
              </div>
            </div>
            <%= ff.hidden_field :date_created, value: Time.now %>
            <div class="per_row_article">
              <div class="row-left">
              </div>
              <div class="row-right">      
                <%= f.submit "Save", class: "btn-save"%>
              </div>
            </div>
            </div>
            <% end %>
      <input id="duration" type="hidden" name="article_duration" />
      <%= hidden_field_tag :course_id, params[:course_id] %>
    <% end %>
  </div>
  <div id="list-articles" class="end">
    <% if @course.articles.count > 0 %>
      <h1>List Articles in "<%= @course.name %>"</h1>
    <% end %>
    <%= render 'course', articles: @course.articles %>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('.js-example-basic-multiple').select2();
  });
  var vid = document.createElement('video');
  $('input[type=file]').change(function () {
    var file = this.files[0];
    const fileType = file['type'];
    const validImageTypes = ['video/mp4'];
    var fileURL = URL.createObjectURL(this.files[0]);
    vid.src = fileURL;
    vid.ondurationchange = function() {
      $('#duration').val(this.duration);
    };
    if (validImageTypes.includes(fileType)) {
      if (file.size > 104857600){
        alert("File size is not allowed bigger than 100Mb");
        this.value = "";
        return false;
      } else {
      }
    }
    else{
      alert(fileType + " is invalid!");
      this.value = "";
      return false;
    }
  });

</script>
<script>
    document.querySelector("input[type=file]")
        .onchange = function(event) {
        let file = event.target.files[0];
        let blobURL = URL.createObjectURL(file);
        document.querySelector("video").src = blobURL;
        document.getElementById('video_upload').style.display = "block";
    }
</script>

app/views/mentor/courses/index.html.erb
<head>
  <title>Edfective.vn - favorite video</title>
  <%= stylesheet_link_tag 'list-course', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="right">
  <h1>
    Webcome back <%= current_user.customer.name  %>
  </h1>
  <a class="btn-save" href="courses/landing_page">
    <i class="fa fa-upload" aria-hidden="true"></i>
    Create course
  </a>
  <br>
  <%index = 0 %>
  <% @mentor_course.each do |mentor_course| %>
    <h1 class="course-name">Course name: <%= link_to mentor_course.name, course_path(mentor_course.slug) %></h1>
    <%index= index + 1%>
    <div id="exampleSlider<%=index %>">
      <div class="MS-content">
        <% @list_article_mentor = Article.joins(:course_articles).where('course_id = ?', mentor_course.id).where.not('articles.video.url' => nil).order(:created_at) %>
        <% @list_article_mentor.each do |article| %>
          <div id="item" class="item per_article">
            <div class="article-left">
              <% if !article.video.url.nil? %>
                <%= cl_video_tag(article.video.instance_variable_get(:@public_id)) %>
              <% else %>
                <%= cl_image_tag('img/some-tips-to-understand-the-need-of-education-erp-software-blog-image564276_ggsimy.png') %>
              <% end %>
            </div>
            <div class="article-right">
              <%= link_to article.title, click_on_article_path(mentor_course.slug, article.id) %>
<!--              <p><%#= article.description %></p>-->
            </div>
<!--            <a href="#">-->
<!--              <i class="fa fa-trash" aria-hidden="true"></i>-->
<!--            </a>-->
          </div>
        <% end %>
      </div>
      <% if mentor_course.articles.count > 2 %>
        <div class="MS-controls">
          <button class="MS-left"><i class="fa fa-chevron-left"></i></button>
          <button class="MS-right"><i class="fa fa-chevron-right" aria-hidden="true"></i></button>
        </div>
      <% end %>
    </div>
  <% end %>


  <div class="paging paging_upload">
    <%== pagy_nav(@pagy) %>

  </div>

  <div class="end">
  </div>
</div>
<script>
    $('#exampleSlider').multislider({
        interval: 100000,
        continuous: false
    });
    $('#exampleSlider1').multislider({
        interval: 10000,
        continuous: false
    });
    $('#exampleSlider2').multislider({
        interval: 10000,
        continuous: false
    });
    $('#exampleSlider3').multislider({
        interval: 10000,
        continuous: false
    });
    $('#exampleSlider4').multislider({
        interval: 10000,
        continuous: false
    });
    $('#exampleSlider5').multislider({
        interval: 10000,
        continuous: false
    });
</script>
</body>

app/views/mentor/courses/landing_page.html.erb
<head>
  <%= stylesheet_link_tag 'upload', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
  <%= cloudinary_js_config %>
</head>
<div class="right">
  <%= render "process", step: @step %>
  <h1>Step 1: Create Course</h1>
  <%= form_with model: @course, html: {:onsubmit =>"myFunction()"}, url: wizard_path, method: :put, local: false do |f| %>
    <div class="create_course">
      <div class="per_row">
        <div class="row-left">
          <h2>Image</h2>
        </div>
        <div class="row-right">
          <div>
            <% if !@course.image.url.nil? %>
              <%= cl_image_tag @course.image, :id => "image-preview"%>
            <% else %>
              <img id="image-preview" src=""/>
            <% end %>
          </div>
          <div class="thum">
            <i class="fa fa-camera" aria-hidden="true"></i>
            <p id="selectedFileName">Upload course image</p>
            <%= f.file_field :image, :value => @course.image, :required => true %>
          </div>
        </div>
      </div>
      <div class="per_row">
        <div class="row-left">
          <h2>Title</h2>
        </div>
        <div class="row-right">
          <%= f.text_field :name, class: "title_article", value: @course.name, :required => true %>
        </div>
      </div>
      <div class="per_row">
        <div class="row-left">
          <h2>Description</h2>
        </div>
        <div class="row-right">
          <%= f.text_area :description, class: "desc_course", value: @course.description, :required => true %>
        </div>
      </div>
      <div class="per_row">
        <div class="row-left">
          <h2>Groups</h2>
        </div>
        <div class="row-right">
          <div>
            <%= f.select :group_ids, Group.name_and_id, {}, {:class => "js-example-basic-multiple", :multiple => "multiple"} %>
          </div>
        </div>
      </div>
      <div class="per_row">
        <div class="row-left">
        </div>
        <div class="row-right">
          <%= f.submit "Save & Continue", class: "btn-save" %>
        </div>
      </div>
      <% if @course.customer_courses.count < 1 %>
        <%= f.fields_for :customer_courses, f.object.customer_courses.build do |ff| %>
          <%= ff.hidden_field :customer_id, value: current_user.id %>
          <%= ff.hidden_field :course_id, value: @course.id %>
          <%= ff.hidden_field :is_owner, value: true %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="end">
  </div>
</div>
<script>

  $('input[type=file]').change(function () {
    var file = this.files[0];
    const fileType = file['type'];
    const validImageTypes = ['image/gif', 'image/jpeg', 'image/png'];
    if (validImageTypes.includes(fileType)) {
      if (file.size > 10485760){
        alert(file.size + "> 10Mb");
        this.value = "";
        $("#image-preview").attr("src", "");
        return false;
      } else {
        $("#image-preview").attr("src", URL.createObjectURL(file));
      }
    }
    else{
      alert(fileType + " is invalid!");
      this.value = "";
      $("#image-preview").attr("src", "");
      return false;
    }
  });

  $(document).ready(function() {
      $('.js-example-basic-multiple').select2();
  });
</script>

app/views/mentor/courses/over_view.html.erb
<head>
    <%= stylesheet_link_tag 'list-course', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'upload', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<div class="right">
    <%= render "process", step: @step %>
    <h1>Step 3: Overview</h1>
    <div class="create_course">
        <div class="per_row">
        <div class="row-left">
            <h2>Image</h2>
        </div>
        <div class="row-right">
            <div class="thum-image">
                <%= cl_image_tag(@course.image, :width => 400) %>
            </div>
        </div>
        </div>
        <div class="per_row">
        <div class="row-left">
            <h2>Courses name</h2>
        </div>
        <div class="row-right">
            <textarea disabled onkeyup="countChar(this)" wrap="hard" rows="2" maxlength="300" class="title_article" name="title"><%= @course.name %></textarea>
        </div>
        </div>
        <div class="per_row">
        <div class="row-left">
            <h2>Description</h2>
        </div>
        <div class="row-right">
            <textarea disabled class="desc_course" name="description" maxlength="300"><%= @course.description %></textarea>
        </div>
        </div>
        <div class="per_row">
        <div class="row-left">
            <h2>Groups</h2>
        </div>
        <div class="row-right">
            <textarea disabled class="desc_course" maxlength="300"><% @course.groups.each do |group| %><%= group.name %>&#10<% end %></textarea>
        </div>
        </div>
        <div class="per_row">
        <div class="row-left">
            <h2>Learning Outcomes</h2>
        </div>
        <div class="row-right">
            <textarea disabled class="desc_course" maxlength="300"><% course_lo_arr = @course.lo.tr('', '').split(';').map(&:to_i) %><% list_lo = Lo.where("id IN (?)", course_lo_arr).group(:id) %><% list_lo.each do |lo| %><%= lo.name %>&#10<% end %></textarea>
        </div>
        </div>
    </div>
    <h2>List articles</h2>
    <div id="exampleSlider1">
    <div class="MS-content">
        <% @course.articles.each do |article| %>
            <% if article.title != nil %>
                <div id="item" class="item per_article">
                    <div class="article-left video_left">
                        <% if !article.video.url.nil? %>
                            <%= video_tag article.video.url, :controls => true %>
                        <% else %>
                        <%= image_tag("course_8.jpg") %>
                        <%#= cl_image_tag("course_8.jpg") %>
                            <%#= cl_video_tag('video/Introduction_to_the_Course_-_Introduction_to_the_Course_-_Coursera_jqhxzg', :effect => "preview", :resource_type => "video") %>
                        <% end %>
                    </div>
                    <div class="article-right">
                        <div href="#">
                            <%= article.title %>
                        </div>
<!--                        <div>-->
                            <%#= article.description %>
<!--                        </div>-->
<!--                        <div>-->
                            <%# article.los.each do |lo| %>
<!--                            <div> <%#= lo.name %> </div>-->
                            <%# end %>
<!--                        </div>-->
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
    <% if @course.articles.count > 2 %>
        <div class="MS-controls">
            <button class="MS-left"><i class="fa fa-chevron-left"></i></button>
            <button class="MS-right"><i class="fa fa-chevron-right" aria-hidden="true"></i></button>
        </div>
    <% end %>
    </div>
    <div class="end">
        <%= link_to "Finish", mentor_courses_path , class: "btn-save" %>
    </div>
</div>

<script>
  $('#exampleSlider1').multislider({
      interval: 100000,
      continuous: false
  });
</script> 

app/views/mentor/courses/update.js.erb
<% if @step.to_s == "create_content" %>
  $('#list-articles').html("<%=j render 'course', articles: @course.articles %>");
<% end %> 