config/routes.rb
Rails.application.routes.draw do
  root "pages#rootpage"


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations'
  }


  resources :topics, only: [:index, :show], param: :slug

  #common routes
  get 'home', to: 'courses#index'
  get 'archived-courses', to: 'customers_courses#archived_courses'
  get 'search', to: 'courses#search'
  get 'profile', to: 'customers#show'
  get 'user-home', to: 'customers_courses#customer_home', :as => :user_home
  get 'search', to: 'courses#search', :as => :search_courses
  put 'comment', to: 'comments#create', :as => :create_comment
  post 'add_customer_path' , to: 'customers_courses#insert_careerpath', :as => :add_customer_path
  get 'get_customer_path' , to: 'customers_courses#insert_careerpath', :as => :get_customer_path

  post 'enroll_courses/:slug', to: 'customers_courses#enroll_courses', :as => :enroll_to_course
  post 'courses/:id', to: 'customers_courses#update', :as => :update_archived
  post 'articles/:id', to: 'customers_articles#update', :as => :update_favor
  post 'comments/:id', to: 'comments#update', :as => :update_comment_pin

  post 'archive_courses/:slug', to: 'customers_courses#add_course_to_archived', :as => :add_to_archived
  post 'favor_articles/:id', to: 'customers_articles#add_to_favor', :as => :add_to_favor
  post 'courses/:slug/articles/:id', to: 'customers_courses#click_on_article', :as => :click_on_article
  post 'time', to: 'customers_articles#time', :as => :update_time
  post "/deactivate", to: "admin/customers#deactivate"
  post "/deactivate_course", to: "admin/courses#deactivate_course"
  post "/deactivate_article", to: "admin/articles#deactivate_article"
  post 'update_customer', to: 'customers#update', :as => :update_customer
  post 'update_img', to: 'customers#update_img', :as => :update_img
  get 'update_path', to: 'customers_courses#update_path', :as => :get_update_path
  post 'insert_customer_lo', to: 'paths#insert_customer_lo', :as => :insert_customer_los



  resources :customers do
  end

  resources :customers_courses do
  end

  resources :customers_articles do
  end

  resources :paths do
  end

  resources :courses, only: [:index, :show, :update], param: :slug do
    resources :articles, only: [:index, :show]
  end


  #mentor routes
  namespace :mentor do
    resources :courses
    resources :articles
  end


  #admin routes
  namespace :admin do
    resources :customers, except: :destroy
    resources :users
    resources :courses
    resources :articles, except: [:create, :destroy]
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::AdminController

  def index
    if current_user.customer.role_id != 1
      redirect_to home_path
    end
    @course = if params[:q].present?
                params[:q].to_i != 0 ? Course.by_id(params[:q]) : Course.search_list(params[:q])
              else
                Course.all
              end
    @pagy, @course_paging = pagy(@course, items: 10)
  end

  def deactivate_course
    @course_disable = Course.friendly.find(params[:slug])
    @course_disable.update(is_active: !@course_disable.is_active)
    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_course, only: [:show]

  def index
    if current_user.present?
      redirect_to user_home_path
    end
    @course = Course.where(:is_active => true).order(number_enrollment: :desc).limit(20)
    @rate_course = Course.where(:is_active => true).order(rate: :desc).limit(20)
    @free_course = Course.where(:is_active => true).where(is_free: true).limit(20)
    @topic = Group.all
    @top_view_article = Article.where(:is_active => true).order(view_number: :desc).limit(20)
  end

  def show
    course_lo_str = Course.where('courses.id = ?', @course.id)
    if course_lo_str.first.lo.present?
      @course_lo_arr = course_lo_str.first.lo.tr('', '').split(';').map(&:to_i)
      @list_lo = Lo.where("id IN (?)", @course_lo_arr).group(:id)
      # @skill = Skill.where("id IN (?)", @list_lo.pluck(:skill_id).uniq)
      lo_req = LoLo.where("lo_id IN (?)", @course_lo_arr)
      req = lo_req.pluck(:lo_req_id).uniq
      @lo_req = Lo.where("id IN (?)", req)
    else
      @lo_req = []
      @list_lo = []
    end

    if current_user.present?
      @check_archived_course = CustomerCourse.where('customer_id = ? AND course_id = ? AND customer_courses.enrollment_date IS null', current_user.id, @course.id)
      if !@check_archived_course.blank?
        @course_detail = Course.select("courses.*, customer_courses.*").joins(:customer_courses).where('customer_id = ? AND course_id = ?', current_user.id, @course.id)
      else
        calculate_progression
      end
    else
      @course_detail = Course.where('course_id = ?', @course.id)
    end
    @list_articles = Article.joins(:courses).where('courses.id = ?', @course.id).where.not('articles.video.url' => nil).order(id: :asc)
    if current_user.present?
      @list_article_viewed = CustomerArticle.joins(:article).where("is_viewed = true AND customer_id = ? AND article_id IN (?) ", current_user.id, @list_articles.ids)
    end
    @pagy, @list_article_paging = pagy(@list_articles, items: 5)
  end

  def calculate_progression
    total_article = Article.joins(:course_articles).where('course_id = ?', @course.id).count
    viewed_article = Article.joins(:course_articles).joins(:customer_articles).where('course_id = ? AND is_viewed = true', @course.id).count
    #fix exception FloatDomainError
    if total_article == 0
      progress = 0
    else
      progress = viewed_article.to_f / total_article.to_f * 100
    end
    @customers_courses_progression = CustomerCourse.where(customer_id: current_user.id, course_id: @course.id)
    @customers_courses_progression.update(progression: progress.round) # => progression
  end

  def search
    if params[:q].present?
      @search_result = Course.search(params[:q])
      @pagy, @search_result_paging = pagy(@search_result, items: 5)
    else
      @search_result = []
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def authenticate_user!
    if user_signed_in?
      # super
    else
      redirect_to user_home_path
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.friendly.find(params[:slug])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:name, :image, :description, :is_free, :is_save, :is_owner, :rate, :number_enrollment, :enrollment_date)
  end

end

app/controllers/mentor/courses_controller.rb
class Mentor::CoursesController < Mentor::MentorController
  include Wicked::Wizard
  before_action :load_course, except: :index
  steps :landing_page, :create_content, :over_view

  def index
    if session[:course_id] != nil
      session[:course_id] = nil
    end
    @pagy ,@mentor_course = pagy(Course.joins(:customer_courses).joins(:customers).where('customers.id = ? AND customer_courses.is_owner = true', current_user.id).order(created_at: :desc), items: 5)
    
  end

  def new
  end

  def show
    @step = step
    if session[:course_id] != nil
      @current_course = @course
    end
    render_wizard
  end

  def update 
    @step = step.to_s
    @course.assign_attributes course_params
    unless step.to_sym == :create_content
      @course.id = Course.last.id.next unless @course.id
      @course.author = current_user.id
      session[:course_id] = @course.id
      begin
        render_wizard @course
      rescue
        flash[:error] = @course.errors.full_messages
      end
    else
      los = []
      @course.articles.each do |article| 
        article.los.each do |lo|
          los << lo.id
        end
      end
      @course.duration += ('%.2f' % (params[:article_duration].to_f / 360 )).to_f
      los = los.uniq
      @course.lo = los.join(";")   
      if step.to_sym == :create_content
        if @course.save
          redirect_to wizard_path(:create_content)
        else
          flash[:error] = @course.errors.full_messages
        end
      end
    end
  end

  private
  def course_params
    params.require(:course).permit!
  end

  def load_course
    if session[:course_id].nil? && step.to_sym != :landing_page
      redirect_to wizard_path(:landing_page)
    elsif step.to_sym == :landing_page && session[:course_id].nil?
        @course = Course.new
    elsif !session[:course_id].nil?
      @course = Course.find_by id: session[:course_id]
      if @course.nil?
        redirect_to mentor_courses_path
      end
    else
      @course = Course.find_by slug: params[:id]
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/search.html.erb
<%= content_for :page_title, 'Search courses' %>
<div class="right">
  <h1>
    Search result for "<%= params[:q] %>"
  </h1>
<!--  <div id="filter_parent" class="filter_parent">-->
<!--    <div id="filter" onclick="filter()" class="filter">-->
<!--      <i class="fa fa-filter" aria-hidden="true"></i>-->
<!--      <span>Filter</span>-->
<!--    </div>-->
<!--    <div id="rating" class="rating">-->
<!--      <div class="rate">-->
<!--        <div class="text-rate">-->
<!--          Rating-->
<!--          <span class="fa fa-star checked"></span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input onclick="addtoFilter(this)" value="4.5" type="radio" name="rate">-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span>4.5 & up</span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input onclick="addtoFilter(this)" value="4.0" type="radio" name="rate">-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span>4.0 & up</span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input onclick="addtoFilter(this)" value="3.5" type="radio" name="rate">-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span>3.5 & up</span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input onclick="addtoFilter(this)" value="3.0" type="radio" name="rate">-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span class="fa fa-star checked"></span>-->
<!--          <span>3.0 & up</span>-->
<!--        </div>-->
<!--      </div>-->
<!--      <div class="price">-->
<!--        <div class="text-rate">-->
<!--          Price-->
<!--          <span class="fa fa-money"></span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input onclick="addtoFilter_Price(this)" type="radio" name="price" value="Free"> <span>Free</span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input onclick="addtoFilter_Price(this)" type="radio" name="price" value="Paid"> <span>Paid</span>-->
<!--        </div>-->
<!--      </div>-->
<!--      <div class="level">-->
<!--        <div class="text-rate">-->
<!--          Level-->
<!--          <span class="fa fa-money"></span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input id="begin" onclick="addtoLevel_1(this)" type="checkbox" value="Beginner"> <span>Beginner</span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input id="inter" onclick="addtoLevel_2(this)" type="checkbox" value="Intermediate"> <span>Intermediate</span>-->
<!--        </div>-->
<!--        <div class="rate_perrow">-->
<!--          <input id="advance" onclick="addtoLevel_3(this)" type="checkbox" value="Advanced"> <span>Advanced</span>-->
<!--        </div>-->
<!--      </div>-->
<!--      <div class="sort_by_anphabet">-->
<!--        <div onclick="addtoSort()" class="text-rate">-->
<!--          Sort-->
<!--          <span id="desc" class="fa fa-sort-alpha-asc"></span>-->
<!--          <span style="display: none;" id="asc" class="fa fa-sort-alpha-desc"></span>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--  <div id="show_filter_parent" onchange="searchByAjax()" class="show_filter">-->
<!--    <span id="show_filter"></span> <i onclick="deleteFilter()" id="show_filter_x"></i>-->
<!--    <span id="show_price"></span><i onclick="deletePrice()" id="show_price_x"></i>-->
<!--    <span id="show_level_begin"></span><i onclick="deleteLevel1()" id="show_begin_x"></i>-->
<!--    <span id="show_level_inter"></span><i onclick="deleteLevel2()" id="show_inter_x"></i>-->
<!--    <span id="show_level_advance"></span><i onclick="deleteLevel3()" id="show_advance_x"></i>-->
<!--    <span id="sort"></span><i onclick="deleteSort()" id="sort_x"></i>-->
<!--    <span onclick="clearAll()" id="clear"> Clear All <i class="fa fa-window-close"></i></span>-->
<!--  </div>-->
  <div class="list-course">
    <% @search_result_paging.each do |course| %>
      <div class="per-course">
        <div class="c-left">
          <% if !course.image.nil? %>
            <%= cl_image_tag(course.image) %>
          <% else %>
            <%= cl_image_tag('img/some-tips-to-understand-the-need-of-education-erp-software-blog-image564276_ggsimy.png') %>
          <% end %>
        </div>
        <div class="c-right">
          <% if current_user.present? %>
            <% customer_course = CustomerCourse.where("customer_id = ? AND course_id = ?", current_user.id, course.id) %>
            <% if customer_course.exists? %>
              <% if customer_course.first.is_save == true %>
                <%= link_to update_archived_path(course.id), method: :post, remote: true do %>
                  <i class="fa fa-bookmark" onclick="bookmark(this,123)" aria-hidden="true"></i>
                <% end %>
              <% else %>
                <%= link_to update_archived_path(course.id), method: :post, remote: true do %>
                  <i class="fa fa-bookmark-o" onclick="bookmark(this,123)" aria-hidden="true"></i>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to add_to_archived_path(course.id), method: :post, remote: true do %>
                <i class="fa fa-bookmark-o" onclick="bookmark(this,123)" aria-hidden="true"></i>
              <% end %>
            <% end %>
          <% else %>

          <% end %>
          <h2><%= link_to course.name, course_path(course) %></h2>
          <p style="margin-bottom: 5px"><%= course.description %></p>
          <p style="font-size: 15px; margin-top: 0px">● Enrollment: <%= course.number_enrollment.to_int.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %> ● Rating: <%= course.rate %></p>

          <% @author = Customer.joins(:customer_courses).where("is_owner = true AND course_id = ? ", course.id).first %>
          <p class="my-name"> Author: <%= @author.name %></p>
          <% rate = course.rate.to_f %>
          <% (1..rate).each do |i| %>
            <% if rate >= i.floor %>
              <span class="fa fa-star checked"></span>
            <% end %>
          <% end %>
          <% if rate != rate.floor %>
            <span class="fa fa-star-half-o checked"></span>
          <% end %>
          <% (1..(5 - rate.ceil)).each do %>
            <span class="fa fa-star-o checked"></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="paging">
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </div>

  <div class="end">
  </div>
</div>

<script>
    function bookmark(bookmark, courseID) {
        var x = bookmark;
        if (x.className === "fa fa-bookmark") {
            x.className = "fa fa-bookmark-o";
        } else {
            x.className = "fa fa-bookmark";
        }
        var app1 = new Vue({
            el: '#app1',
            mounted: function () {
                axios.get('/archive_courses/', {
                    params: {
                        num: courseID
                    }
                }).catch(error => {
                    console.log(error);
                });
            }
        });
    }
</script>

<script>
    function filter() {
        var x = document.getElementById('rating');
        var displayValue = window.getComputedStyle(x).visibility;
        if (displayValue == "hidden") {
            document.getElementById('rating').style.visibility = "visible";
            document.getElementById('show_filter_parent').style.visibility = "visible";
            document.getElementById('filter_parent').style.height = "auto";
            document.getElementById('show_filter_parent').style.height = "30px";
        } else {
            document.getElementById('rating').style.visibility = "hidden";
            document.getElementById('show_filter_parent').style.visibility = "hidden";
            document.getElementById('show_filter_parent').style.height = "0px";
            document.getElementById('filter_parent').style.height = "55px";

        }
    }

    function changeSort() {
        if (document.getElementById('desc').style.display == "none") {
            document.getElementById('desc').style.display = "inline-block";
        } else {
            document.getElementById('desc').style.display = "none";

        }
        if (document.getElementById('asc').style.display == "none") {
            document.getElementById('asc').style.display = "inline-block";
        } else {
            document.getElementById('asc').style.display = "none";
        }
    }

    function addtoSort() {
        if (document.getElementById('sort').textContent.includes('a-z')) {
            document.getElementById('sort').innerText = "Sort: z-a ";
            document.getElementById('sort_x').className = "fa fa-window-close";
        } else {
            document.getElementById('sort').innerText = "Sort: a-z ";
            document.getElementById('sort_x').className = "fa fa-window-close";
        }
    }

    function addtoFilter(rate) {
        var x = rate.value;
        document.getElementById('show_filter').innerText = "Rating: " + x;
        document.getElementById('show_filter_x').className = "fa fa-window-close";
    }

    function addtoFilter_Price(price) {
        var x = price.value;
        document.getElementById('show_price').innerText = "Price: " + x + " ";
        document.getElementById('show_price_x').className = "fa fa-window-close";
    }

    function addtoLevel_1(level) {
        var x = level.value;

        if (document.getElementById('show_level_begin').textContent.includes(x)) {
            document.getElementById('show_level_begin').innerText = "";
            document.getElementById('show_begin_x').className = "";
        } else {
            document.getElementById('show_level_begin').innerText = "#" + x + " ";
            document.getElementById('show_begin_x').className = "fa fa-window-close";
        }
    }

    function addtoLevel_2(level) {
        var x = level.value;
        if (document.getElementById('show_level_inter').textContent.includes(x)) {
            document.getElementById('show_level_inter').innerText = "";
            document.getElementById('show_inter_x').className = "";
        } else {
            document.getElementById('show_level_inter').innerText = "#" + x + " ";
            document.getElementById('show_inter_x').className = "fa fa-window-close";
        }
    }

    function addtoLevel_3(level) {
        var x = level.value;
        if (document.getElementById('show_level_advance').textContent.includes(x)) {
            document.getElementById('show_level_advance').innerText = "";
            document.getElementById('show_advance_x').className = "";
        } else {
            document.getElementById('show_level_advance').innerText = "#" + x + " ";
            document.getElementById('show_advance_x').className = "fa fa-window-close";
        }
    }

    function deleteFilter() {
        document.getElementById('show_filter').innerText = "";
        document.getElementById('show_filter_x').className = "";
        var ele = document.getElementsByName('rate');
        for (i = 0; i < ele.length; i++) {
            ele[i].checked = false;
        }
    }

    function deletePrice() {
        document.getElementById('show_price').innerText = "";
        document.getElementById('show_price_x').className = "";
        var ele = document.getElementsByName('price');
        for (i = 0; i < ele.length; i++) {
            ele[i].checked = false;
        }
    }

    function deleteLevel1() {
        document.getElementById('show_level_begin').innerText = "";
        document.getElementById('show_begin_x').className = "";
        document.getElementById("begin").checked = false;

    }

    function deleteLevel2() {
        document.getElementById('show_level_inter').innerText = "";
        document.getElementById('show_inter_x').className = "";
        document.getElementById("inter").checked = false;
    }

    function deleteLevel3() {
        document.getElementById('show_level_advance').innerText = "";
        document.getElementById('show_advance_x').className = "";
        document.getElementById("advance").checked = false;
    }

    function deleteSort() {
        document.getElementById('sort').innerText = "";
        document.getElementById('sort_x').className = "";
    }

    function clearAll() {
        deleteLevel1();
        deleteLevel2();
        deleteLevel3();
        deleteSort();
        deletePrice();
        deleteFilter();

    }


</script>

app/views/courses/show.html.erb
<head>
  <%= stylesheet_link_tag 'course_detail', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'course_detail', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<div class="right">
  <div class="top">
    <h1><%= @course.name %></h1>
    <span>by</span>
    <% @author = Customer.joins(:customer_courses).where("is_owner = true AND course_id IN (?)  ", @course.id).first %>
    <span><%= @author.name %></span>
    <div class="intro">
      <% if !@course.image.nil? %>
        <%= cl_image_tag(@course.image) %>
      <% else %>
        <%= cl_image_tag('img/some-tips-to-understand-the-need-of-education-erp-software-blog-image564276_ggsimy.png') %>
      <% end %>
      <span id="des" onclick="showmore()"><%= @course.description %><br></span>
<!--      <br>-->
<!--      ● Number enroll: <%#= @course.number_enrollment.to_int.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %>-->
<!--      <br>-->
<!--      ● Rating: <%#= @course.rate %><br>-->
<!--      ● Duration: <%#= @course.duration %> hours on-demand video-->
<!--      <br>-->
      <table class="show_weight">
        <tr>
          <td><i class="fa fa-check-square" aria-hidden="true"></i>Number enroll:</td>
          <td><%= @course.number_enrollment.to_int.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %> enrollments</td>
        </tr>
        <tr>
          <td><i class="fa fa-check-square" aria-hidden="true"></i>Rating:</td>
          <td style="display: flex">
            <%= @course.rate %>
            <% rate = @course.rate %>
            <% (1..rate).each do |i| %>
              <% if rate >= i.floor %>
                <span class="fa fa-star checked"></span>
              <% end %>
            <% end %>
            <% if rate != rate.floor %>
              <span class="fa fa-star-half-o checked"></span>
            <% end %>
            <% (1..(5 - rate.ceil)).each do %>
              <span class="fa fa-star-o checked"></span>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><i class="fa fa-check-square" aria-hidden="true"></i>Duration:</td>
          <td><%= @course.duration %> hours</td>
        </tr>
      </table>
      <h2>Requirements</h2>
        <% @lo_req.each do |lo_req| %>
         <div class="show_require"> <i class="fa fa-dot-circle-o" aria-hidden="true"></i>
            <%= lo_req.name %>
        </div>
      <% end %>
<!--      <div class="skill_set">-->
<!--        <h2>Requirements</h2>-->
<!--        <ul>-->
          <%# @lo_req.each do |lo_req| %>
<!--            <li>-->
<!--            <span class="out_side_level">-->
              <%#= lo_req.name %>
<!--                </span>-->
<!--            </li>-->
          <%# end %>
<!--        </ul>-->
<!--      </div>-->
    </div>
    <% if current_user.present? %>
      <% check_archived_course = CustomerCourse.where('customer_id = ? AND course_id = ? AND enrollment_date IS NOT null', current_user.id, @course.id) %>
      <% if check_archived_course.blank? %>
      <% else %>
        <!--       user enrolled in course-->
        <% check_archived_course.each do |course_detail| %>
          <p>Progress(<%= course_detail.progression %>%)</p>
          <progress max="100" value="<%= course_detail.progression %>"></progress>
        <% end %>
      <% end %>
    <% end %>
    <%= button_to enroll_to_course_path(@course.id), method: :post do %>
      Start learn
    <% end %>
    <div class="skill_set">
      <h2>What you'll learn:</h2>
      <ul>
        <% @list_lo.each do |lo| %>
          <li>
            <span class="out_side_level">
              <%= lo.name %>
                </span>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
  <div class="buttom">
    <h2>List Article in '<%= @course.name %>'</h2>
    <% @list_article_paging.each do |a| %>
      <div class="per-course">
        <div class="c-left">
          <a href="#">
            <% if !a.video.url.nil? %>
            <%= cl_video_tag(a.video.instance_variable_get(:@public_id), :effect => "preview", :resource_type => "video") %>
            <% else %>
              <%= cl_video_tag('video/Introduction_to_the_Course_-_Introduction_to_the_Course_-_Coursera_jqhxzg', :effect => "preview", :resource_type => "video") %>
            <% end %>
          </a>
        </div>
        <div class="c-right">
          <%= link_to a.title, click_on_article_path(@course, a.id) %>
          <span>
          <%= a.description %>
        </span>
        </div>
        <i class="fa fa-check-circle" aria-hidden="true"></i>
      </div>
    <% end %>
  </div>
  <div class="paging">
    <% if @list_articles.ids.count > 5 %>
      <%== pagy_nav(@pagy) %>
    <% else %>
    <% end %>
  </div>
  <div class="end">
  </div>
</div>
<script>
    var count = -1;
    <% @list_article_paging.each do | full | %>
    count++;
    <%   if current_user.present? %>
    <% @list_article_viewed.each do |view| %>
    <% if view.article_id == full.id %>
    document.querySelectorAll('.fa-check-circle')[count].style.display = 'inline-block';
    <% end %>
    <% end %>
    <% end %>
    <% end %>

    function showmore() {
        if (document.getElementById('des').style.webkitLineClamp == "inherit") {
            document.getElementById('des').style.webkitLineClamp = "12";
        } else {
            document.getElementById('des').style.webkitLineClamp = "inherit";
        }

    }
</script>

<script>

</script>

<script>
    var perfEntries = performance.getEntriesByType("navigation");

    if (perfEntries[0].type === "back_forward") {
        location.reload(true);
    }
</script>